# Generated by Django 3.0 on 2020-02-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200225_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='order',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
